language: php

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
