language: php
os:
  - linux
  - osx
php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - composer test

after_success:
    - bash <(curl -s https://codecov.io/bash)
